apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: webhook-receiver # This matches the 'app: my-app' label in your Deployment's pod template
  ports:
    - protocol: TCP
      port: 8080       # The port the Service itself exposes
      targetPort: 8080 # The container port to which traffic is forwarded
  type: ClusterIP # Use 'LoadBalancer' or 'NodePort' to expose outside the cluster
